# Base Python image
FROM python:3.11

# Copy the application code
WORKDIR /app
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the gRPC server port
EXPOSE 50051

# Run the gRPC server
CMD ["python", "grpc_server.py"]
