# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'query_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13query_service.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\rQueryResponse\x12\x10\n\x08query_id\x18\x01 \x01(\t\"/\n\x0bQueryResult\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\"\x0e\n\x0c\x45mptyRequest2x\n\x0cQueryService\x12,\n\x0bSubmitQuery\x12\r.QueryRequest\x1a\x0e.QueryResponse\x12:\n\x10GetQueryResponse\x12\x16.google.protobuf.Empty\x1a\x0c.QueryResult0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=52
  _globals['_QUERYREQUEST']._serialized_end=81
  _globals['_QUERYRESPONSE']._serialized_start=83
  _globals['_QUERYRESPONSE']._serialized_end=116
  _globals['_QUERYRESULT']._serialized_start=118
  _globals['_QUERYRESULT']._serialized_end=165
  _globals['_EMPTYREQUEST']._serialized_start=167
  _globals['_EMPTYREQUEST']._serialized_end=181
  _globals['_QUERYSERVICE']._serialized_start=183
  _globals['_QUERYSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
